### PR TITLE
Issue #3 - Tracking encoding exceptions

### PR DESCRIPTION
**Pull request by Yoric**

### CODE REVIEW

**Review by arai-a — APPROVED** [review]
Just to make sure, is there any other failure after extending recursion limit?

**Comment by Yoric** [comment]
@arai-a After extending the recursion limit and skipping empty files, I see a sharp decrease in failures. I don't know yet if any remain, as the entire test takes ~6h, but for the first ~900 files (out of ~26,000), I don't see any error yet.

**Comment by dominiccooney** [comment]
This is mostly IO so you should be able to cut that time down using Python's threadpool or even just making the post-dictionary bit process a single file and run it with GNU parallel on the command line.

**Comment by Yoric** [comment]
Confirmed fix. I'm now out of exceptions in the Python code.

**Comment by Yoric** [comment]
>  This  is mostly IO so you should be able to cut that time down using Python's  threadpool or even just making the post-dictionary bit process a single  file and run it with GNU parallel on the command line.

Thanks for the suggestion. I don't think I'm going to spend too much time optimizing this codebase, though, since we're still planning to port it to Rust (and merge the algorithms/formats – see https://github.com/binast/binjs-fbssdc/issues/2) in a few weeks time.

**Pull request merged**
